const translations = {
    en: {
     'home': 'Home',
      'sectors': 'Sectors',
      'aboutUs': 'About us',
      'offer': 'What we offer',
      'new': 'Novelties',
      'blog': 'Blog',
      'contact': 'Контакт',
      'structural_reform': 'Оценка на организационния модел на централната администрация на изпълнителната власт',
      'NAMRB': 'Примерни модели за административни структури на седем групи общини и проекти на документи за организационното им развитие',
      'consulting_services': 'Подобряване на ефективността и оптимизиране на структурата на администрацията на Министерството на външните работи',
      'organizational': 'Организационна оценка и планиране на подобрения',
      'analyze': 'Консолидиран анализ на организационното състояние на Министерство на отбраната',
      'actual_standarts': 'Актуализирани стандарти за провеждане на граждански консултации',
      'nfk': 'Анализ и оценка на въздействието на действащото законодателство за НФК',
      'impact_assessment': 'Цялостна предварителна оценка на въздействието във връзка с регулиране на основни икономически сектори',
      'preliminary': 'Цялостна предварителна оценка на въздействието във връзка с регулиране на основни икономически сектори',
      'org_model': 'Нов организационен модел на НСОРБ',
      'functional_analyze': 'Функционални анализи',
      'action_plan': 'План за оценка на програма за морско дело, рибарство и аквакултури',
      'elec_networks': 'Социалноикономически анализ и обобщен доклад с резултати от проект „Опазване на застрашени видове птици чрез обезопасяване на опасни за тях въздушни електропроводи в защитени зони от НАТУРА 2000 в Западна България/ LIFE BIRDS ON POWER LINES“',
      'strategic': 'Последваща оценка за изпълнението на националната стратегия за регионално развитие за периода 2012-2022 г.',
      'reg_plans': 'Последващи оценки на регионалните планове за развитие (РПР) 2014 – 2020 г.',
      'integrated_dev': 'Планове за интегрирано развитие на общини за периода 2021-2027',
      'tech_roadmaps': 'Технологични пътни карти, свързани с идентифицираните тематични области в Иновационната стратегия за интелигентна специализация',
      'accreditation_law_analysis': 'Проучване и анализ на новото законодателство в областта на акредитацията',
      'nfc': 'Законодателна промяна в правната рамка на НФК',
      'nif_calls_analysis_impact': 'Анализ на пет конкурсни сесии на Националния иновационен фонд и оценка на ефекта от изпълнението договорите',
      'training_managing_authority_opta': 'Обучения за повишаване на квалификацията на служителите на Управляващия орган на Оперативна програма „Техническа помощ“',
      'eures_network_research_evaluation': 'Проучване и оценка на Мрежата Европейски услуги за заетост (EURES)',
      'technology_audit_rnd_capabilities_ict': 'Технологичен одит на способностите за изследователска и развойна дейност в информационните и комуникационните технологии (ИКТ)',
      'evaluation_measures_deinstitutionalisation_social_inclusion': 'Оценка на мерките за деинституционализация и насърчаване на социалното включване',
      'danube_bridge_vidin_calafat_strategy': 'Стратегия за развитие на Дунав мост Видин-Калафат АД за периода 2018 – 2026 г. И прилежащ бизнес план',
      'review_administrative_register_websites': 'Преглед на информацията в Административния регистър и интернет страниците на администрациите',
      'judicial_independence_measures': 'Въвеждане на мерки за повишаване на независимостта на съдебната власт',
      'housing_policy_concept_sofia': 'Концепция за жилищна политика на Столична община',
      'digital_platform_interaction_analysis': 'Дигитална платформа за анализ на потенциални лекарствени взаимодействия',
      'digital_competence_certification_module': 'Модул за сертифициране на цифрова компетентност',
      'cms_portal_ministry_transport_communications': 'Проектиране, разработване и внедряване на система за управление на съдържанието и създаване на портал на министерство на транспорта и съобщенията',
      'intellectual_property_protection_campaigns': 'Кампании за защита на интелектуалната собственост',
      'eu_common_agricultural_policy_campaigns': 'Кампании за общата селскостопанска политика на Европейския съюз',
    },
    es: {
    'home': 'Начало',
      'sectors': 'Сектори',
      'aboutUs': 'За нас',
      'offer': 'Какво предлагаме',
      'new': 'Новости',
      'blog': 'Блог',
      'contact': 'Контакт',
      'structural_reform': 'Оценка на организационния модел на централната администрация на изпълнителната власт',
      'NAMRB': 'Примерни модели за административни структури на седем групи общини и проекти на документи за организационното им развитие',
      'consulting_services': 'Подобряване на ефективността и оптимизиране на структурата на администрацията на Министерството на външните работи',
      'organizational': 'Организационна оценка и планиране на подобрения',
      'analyze': 'Консолидиран анализ на организационното състояние на Министерство на отбраната',
      'actual_standarts': 'Актуализирани стандарти за провеждане на граждански консултации',
      'nfk': 'Анализ и оценка на въздействието на действащото законодателство за НФК',
      'impact_assessment': 'Цялостна предварителна оценка на въздействието във връзка с регулиране на основни икономически сектори',
      'preliminary': 'Цялостна предварителна оценка на въздействието във връзка с регулиране на основни икономически сектори',
      'org_model': 'Нов организационен модел на НСОРБ',
      'functional_analyze': 'Функционални анализи',
      'action_plan': 'План за оценка на програма за морско дело, рибарство и аквакултури',
      'elec_networks': 'Социалноикономически анализ и обобщен доклад с резултати от проект „Опазване на застрашени видове птици чрез обезопасяване на опасни за тях въздушни електропроводи в защитени зони от НАТУРА 2000 в Западна България/ LIFE BIRDS ON POWER LINES“',
      'strategic': 'Последваща оценка за изпълнението на националната стратегия за регионално развитие за периода 2012-2022 г.',
      'reg_plans': 'Последващи оценки на регионалните планове за развитие (РПР) 2014 – 2020 г.',
      'integrated_dev': 'Планове за интегрирано развитие на общини за периода 2021-2027',
      'tech_roadmaps': 'Технологични пътни карти, свързани с идентифицираните тематични области в Иновационната стратегия за интелигентна специализация',
      'accreditation_law_analysis': 'Проучване и анализ на новото законодателство в областта на акредитацията',
      'nfc': 'Законодателна промяна в правната рамка на НФК',
      'nif_calls_analysis_impact': 'Анализ на пет конкурсни сесии на Националния иновационен фонд и оценка на ефекта от изпълнението договорите',
      'training_managing_authority_opta': 'Обучения за повишаване на квалификацията на служителите на Управляващия орган на Оперативна програма „Техническа помощ“',
      'eures_network_research_evaluation': 'Проучване и оценка на Мрежата Европейски услуги за заетост (EURES)',
      'technology_audit_rnd_capabilities_ict': 'Технологичен одит на способностите за изследователска и развойна дейност в информационните и комуникационните технологии (ИКТ)',
      'evaluation_measures_deinstitutionalisation_social_inclusion': 'Оценка на мерките за деинституционализация и насърчаване на социалното включване',
      'danube_bridge_vidin_calafat_strategy': 'Стратегия за развитие на Дунав мост Видин-Калафат АД за периода 2018 – 2026 г. И прилежащ бизнес план',
      'review_administrative_register_websites': 'Преглед на информацията в Административния регистър и интернет страниците на администрациите',
      'judicial_independence_measures': 'Въвеждане на мерки за повишаване на независимостта на съдебната власт',
      'housing_policy_concept_sofia': 'Концепция за жилищна политика на Столична община',
      'digital_platform_interaction_analysis': 'Дигитална платформа за анализ на потенциални лекарствени взаимодействия',
      'digital_competence_certification_module': 'Модул за сертифициране на цифрова компетентност',
      'cms_portal_ministry_transport_communications': 'Проектиране, разработване и внедряване на система за управление на съдържанието и създаване на портал на министерство на транспорта и съобщенията',
      'intellectual_property_protection_campaigns': 'Кампании за защита на интелектуалната собственост',
      'eu_common_agricultural_policy_campaigns': 'Кампании за общата селскостопанска политика на Европейския съюз',
    },
    bg: {
      'home': 'Начало',
      'sectors': 'Сектори',
      'aboutUs': 'За нас',
      'offer': 'Какво предлагаме',
      'new': 'Новости',
      'blog': 'Блог',
      'contact': 'Контакт',
      'structural_reform': 'Оценка на организационния модел на централната администрация на изпълнителната власт',
      'NAMRB': 'Примерни модели за административни структури на седем групи общини и проекти на документи за организационното им развитие',
      'consulting_services': 'Подобряване на ефективността и оптимизиране на структурата на администрацията на Министерството на външните работи',
      'organizational': 'Организационна оценка и планиране на подобрения',
      'analyze': 'Консолидиран анализ на организационното състояние на Министерство на отбраната',
      'actual_standarts': 'Актуализирани стандарти за провеждане на граждански консултации',
      'nfk': 'Анализ и оценка на въздействието на действащото законодателство за НФК',
      'impact_assessment': 'Цялостна предварителна оценка на въздействието във връзка с регулиране на основни икономически сектори',
      'preliminary': 'Цялостна предварителна оценка на въздействието във връзка с регулиране на основни икономически сектори',
      'org_model': 'Нов организационен модел на НСОРБ',
      'functional_analyze': 'Функционални анализи',
      'action_plan': 'План за оценка на програма за морско дело, рибарство и аквакултури',
      'elec_networks': 'Социалноикономически анализ и обобщен доклад с резултати от проект „Опазване на застрашени видове птици чрез обезопасяване на опасни за тях въздушни електропроводи в защитени зони от НАТУРА 2000 в Западна България/ LIFE BIRDS ON POWER LINES“',
      'strategic': 'Последваща оценка за изпълнението на националната стратегия за регионално развитие за периода 2012-2022 г.',
      'reg_plans': 'Последващи оценки на регионалните планове за развитие (РПР) 2014 – 2020 г.',
      'integrated_dev': 'Планове за интегрирано развитие на общини за периода 2021-2027',
      'tech_roadmaps': 'Технологични пътни карти, свързани с идентифицираните тематични области в Иновационната стратегия за интелигентна специализация',
      'accreditation_law_analysis': 'Проучване и анализ на новото законодателство в областта на акредитацията',
      'nfc': 'Законодателна промяна в правната рамка на НФК',
      'nif_calls_analysis_impact': 'Анализ на пет конкурсни сесии на Националния иновационен фонд и оценка на ефекта от изпълнението договорите',
      'training_managing_authority_opta': 'Обучения за повишаване на квалификацията на служителите на Управляващия орган на Оперативна програма „Техническа помощ“',
      'eures_network_research_evaluation': 'Проучване и оценка на Мрежата Европейски услуги за заетост (EURES)',
      'technology_audit_rnd_capabilities_ict': 'Технологичен одит на способностите за изследователска и развойна дейност в информационните и комуникационните технологии (ИКТ)',
      'evaluation_measures_deinstitutionalisation_social_inclusion': 'Оценка на мерките за деинституционализация и насърчаване на социалното включване',
      'danube_bridge_vidin_calafat_strategy': 'Стратегия за развитие на Дунав мост Видин-Калафат АД за периода 2018 – 2026 г. И прилежащ бизнес план',
      'review_administrative_register_websites': 'Преглед на информацията в Административния регистър и интернет страниците на администрациите',
      'judicial_independence_measures': 'Въвеждане на мерки за повишаване на независимостта на съдебната власт',
      'housing_policy_concept_sofia': 'Концепция за жилищна политика на Столична община',
      'digital_platform_interaction_analysis': 'Дигитална платформа за анализ на потенциални лекарствени взаимодействия',
      'digital_competence_certification_module': 'Модул за сертифициране на цифрова компетентност',
      'cms_portal_ministry_transport_communications': 'Проектиране, разработване и внедряване на система за управление на съдържанието и създаване на портал на министерство на транспорта и съобщенията',
      'intellectual_property_protection_campaigns': 'Кампании за защита на интелектуалната собственост',
      'eu_common_agricultural_policy_campaigns': 'Кампании за общата селскостопанска политика на Европейския съюз',
      
    }
  };

 const lang = 'bg'; // 'en' or 'bg' as needed

  // breadcrumb trails for each page
  const breadcrumbMap = {
    'index.html': ['home'],
    'aboutUs.html': ['home', 'aboutUs'],
    'offer.html': ['home', 'offer'],
    'new.html': ['home', 'new'],
    'blog.html': ['home', 'blog'],
    'sectors.html': ['home', 'sectors'],
    'structural_reform.html': ['home', 'sectors', 'structural_reform'],
    'NAMRB.html': ['home', 'sectors', 'NAMRB'],
    'consulting_services.html': ['home', 'offer', 'consulting_services'],
    'organizational.html': ['home', 'sectors', 'organizational'],
    'analyze.html': ['home', 'offer', 'analyze'],
    'actual_standarts.html': ['home', 'offer', 'actual_standarts'],
    'nfk.html': ['home', 'offer', 'nfk'],
    'impact_assessment.html': ['home', 'offer', 'impact_assessment'],
    'preliminary.html': ['home', 'offer', 'preliminary'],
    'org_model.html': ['home', 'offer', 'org_model'],
    'functional_analyze.html': ['home', 'offer', 'functional_analyze'],
    'action_plan.html': ['home', 'offer', 'action_plan'],
    'elec_networks.html': ['home', 'sectors', 'elec_networks'],
    'strategic.html': ['home', 'offer', 'strategic'],
    'reg_plans.html': ['home', 'offer', 'reg_plans'],
    'integrated_dev.html': ['home', 'offer', 'integrated_dev'],
    'tech_roadmaps.html': ['home', 'offer', 'tech_roadmaps'],
    'accreditation_law_analysis.html': ['home', 'offer', 'accreditation_law_analysis'],
    'nfc.html': ['home', 'offer', 'nfc'],
    'nif_calls_analysis_impact.html': ['home', 'offer', 'nif_calls_analysis_impact'],
    'training_managing_authority_opta.html': ['home', 'offer', 'training_managing_authority_opta'],
    'eures_network_research_evaluation.html': ['home', 'offer', 'eures_network_research_evaluation'],
    'technology_audit_rnd_capabilities_ict.html': ['home', 'offer', 'technology_audit_rnd_capabilities_ict'],
    'evaluation_measures_deinstitutionalisation_social_inclusion.html': ['home', 'offer', 'evaluation_measures_deinstitutionalisation_social_inclusion'],
    'danube_bridge_vidin_calafat_strategy.html': ['home', 'offer', 'danube_bridge_vidin_calafat_strategy'],
    'judicial_independence_measures.html': ['home', 'offer', 'judicial_independence_measures'],
    'review_administrative_register_websites.html': ['home', 'offer', 'review_administrative_register_websites'],
    'housing_policy_concept_sofia.html': ['home', 'offer', 'housing_policy_concept_sofia'],
    'digital_platform_interaction_analysis.html': ['home', 'offer', 'digital_platform_interaction_analysis'],
    'digital_competence_certification_module.html': ['home', 'offer', 'digital_competence_certification_module'],
    'cms_portal_ministry_transport_communications.html': ['home', 'offer', 'cms_portal_ministry_transport_communications'],
    'intellectual_property_protection_campaigns.html': ['home', 'offer', 'intellectual_property_protection_campaigns'],
    'eu_common_agricultural_policy_campaigns.html': ['home', 'offer', 'eu_common_agricultural_policy_campaigns'],

   
  };
  

  // Renders breadcrumbs based on lang + translations
function renderBreadcrumb(lang, translations) {
  const currentPath = window.location.pathname.split('/').pop();
  const trail = breadcrumbMap[currentPath];
  const breadcrumb = document.getElementById('breadcrumb');
  let html = `<ol class="breadcrumb-list">`; 

  if (trail && trail.length > 0) {
    trail.forEach((key, index) => {
      const label = translations[lang]?.[key] || key;
      const isLast = index === trail.length - 1;

      const hrefMap = {
        home: 'index.html',
        offer:'offer.html',
        sectors: 'sectors.html',
        structural_reform: 'structural_reform.html',
        NAMRB: 'NAMRB.html',
        consulting_services: 'consulting_services.html',
        organizational: 'organizational.html',
        analyze: 'analyze.html',
        actual_standarts: 'actual_standarts.html',
        nfk: 'nfk.html',
        impact_assessment: 'impact_assessment.html',
        preliminary: 'preliminary.html',
        org_model: 'org_model.html',
        functional_analyze: 'functional_analyze.html',
        action_plan: 'action_plan.html',
        elec_networks: 'elec_networks.html',
        strategic: 'strategic.html',
        reg_plans: 'reg_plans.html',
        integrated_dev: 'integrated_dev.html',
        tech_roadmaps: 'tech_roadmaps.html',
        accreditation_law_analysis: 'accreditation_law_analysis.html',
        nfc: 'nfc.html',
        nif_calls_analysis_impact: 'nif_calls_analysis_impact.html',
        training_managing_authority_opta: 'training_managing_authority_opta.html',
        eures_network_research_evaluation: 'eures_network_research_evaluation.html',
        technology_audit_rnd_capabilities_ict: 'technology_audit_rnd_capabilities_ict.html',
        evaluation_measures_deinstitutionalisation_social_inclusion: 'evaluation_measures_deinstitutionalisation_social_inclusion.html',
        danube_bridge_vidin_calafat_strategy: 'danube_bridge_vidin_calafat_strategy.html',
        judicial_independence_measures: 'judicial_independence_measures.html',
        review_administrative_register_websites: 'review_administrative_register_websites.html',
        housing_policy_concept_sofia: 'housing_policy_concept_sofia.html',
        digital_platform_interaction_analysis: 'digital_platform_interaction_analysis.html',
        digital_competence_certification_module: 'digital_competence_certification_module.html',
        cms_portal_ministry_transport_communications: 'cms_portal_ministry_transport_communications.html',
        intellectual_property_protection_campaigns:'intellectual_property_protection_campaigns.html',
        eu_common_agricultural_policy_campaigns:'eu_common_agricultural_policy_campaigns.html'
      };

      if (isLast) {
        html += `<li aria-current="page" class="truncate" title="${label}">${label}</li>`;
      } else {
        html += `<li><a href="${hrefMap[key]}" class="truncate" title="${label}">${label}</a></li>`;
      }
    });
  }

  html += `</ol>`;
  breadcrumb.innerHTML = html;
}

  //---END 